server:
  port: 80
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      force: true
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
logging:
  level:
    root: error